### ISSUE TITLE
logLevel parameter ignored

### ISSUE THREAD

**Issue by mrsiejas** [opsgenie/kubernetes-event-exporter#100]
I'm trying to figure out why we are receiving a `Warning` type of messages even though the config file is set to use `logLevel: error` on should filter out events with lower severity.

```
config.yaml:
----
logFormat: json
logLevel: error
receivers:
- name: webhook_alert
  webhook:
    endpoint: https://hooks.slack.com/services/one/two/three
    layout:
      text: |-
        DevEksCluster
        *{{ .Type }}*
        {{ .Reason }} {{ .InvolvedObject.Kind }}/{{ .InvolvedObject.Name }}
        {{ .Message }}
- file:
    path: /dev/stdout
  name: dump
route:
  routes:
  - drop:
    - namespace: '*'
    - type: Normal
    match:
    - receiver: webhook_alert
    - receiver: dump
```

here is a snippet of the event from the stdout dump
```
...
    "firstTimestamp": "2020-12-04T20:53:38Z",
    "lastTimestamp": "2020-12-19T14:58:48Z",
    "count": 83153,
    "type": "Warning",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": "",
    "involvedObject": {
...
 ```
