### ISSUE TITLE
Route config to match many namespaces

### ISSUE THREAD

**Issue by mrsiejas** [opsgenie/kubernetes-event-exporter#106]
Is there a way to match many namespaces via routes? For example I would like to allow traffic from namespace: kube-system and control-center with type Warning. Some combinations I've tried with no luck:

```
route:
  routes:
  - drop:
    - type: Normal
    match:
    - namespace: control-center
      receiver: webhook_alert
  - drop:
    - type: Normal
    match:
    - namespace: kube-system
      receiver: webhook_alert
```

```
route:
  routes:
  - drop:
    - type: Normal
    match:
    - receiver: webhook_alert
    namespace: control-center
  - drop:
    - type: Normal
    match:
    - receiver: webhook_alert
    namespace: kube-system
```
    
```
route:
  routes:
  - drop:
    - type: Normal
    match:
    - namespace: control-center
    - namespace: kube-system
    - namespace: monitoring
    - namespace: cattle-system
    - namespace: default
    - namespace: prod-qa
    - receiver: webhook_alert
 ```
 
 ```
 route:
  routes:
  - drop:
    - type: Normal
    match:
    - namespace: control-center
    - receiver: webhook_alert
  - drop:
    - type: Normal
    match:
    - namespace: kube-system
    - receiver: webhook_alert
 ```
