### ISSUE TITLE
timestamp field is not working in elasticsearch

### ISSUE THREAD

**Issue by sohel2020** [opsgenie/kubernetes-event-exporter#124]
Elasticsearch version: 6.8.0
configuration:
```yaml
  - name: "elasticsearch"
    elasticsearch:
      hosts:
      - http://localhost:9200
      index: kube-events
      indexFormat: "kube-events-{2006-01-02}"
      layout:
        message: "{{ .Message }}"
        reason: "{{ .Reason }}"
        type: "{{ .Type }}"
        count: "{{ .Count }}"
        kind: "{{ .InvolvedObject.Kind }}"
        name: "{{ .InvolvedObject.Name }}"
        namespace: "{{ .Namespace }}"
        component: "{{ .Source.Component }}"
        host: "{{ .Source.Host }}"
        labels: "{{ toJson .InvolvedObject.Labels}}"
```

**Comment by sohel2020** [comment]
when I'm using layout then it's not working. without layout it is working. with layout it's not sending the following fields
```yaml
    "fields":{
        "firstTimestamp":[
            "2021-06-01T07:06:05.000Z"
        ],
        "metadata.creationTimestamp":[
            "2021-06-01T07:06:05.000Z"
        ],
        "lastTimestamp":[
            "2021-06-01T07:06:05.000Z"
        ],
        "metadata.managedFields.time":[
            "2021-06-01T07:06:05.000Z"
        ]
    }
```

**Comment by neolunar7** [comment]
I'm having similar issue, but a bit different. When I don't specify layout, the fields eventtime, firsttimestamp, lasttimestamp is correctly put into the documents. However, many events get filtered, which I don't know why.

**Comment by neolunar7** [comment]
How I came to know some events are filtered, is that if I only specify field as below,
```
      layout:
        message: "{{ .Message }}"
        reason: "{{ .Reason }}"
        type: "{{ .Type }}"
        count: "{{ .Count }}"
        kind: "{{ .InvolvedObject.Kind }}"
        name: "{{ .InvolvedObject.Name }}"
```
I get much more events.
