### ISSUE TITLE
Event Exporter not getting node events

### ISSUE THREAD

**Issue by cmichr** [opsgenie/kubernetes-event-exporter#138]
Event Exporter is able to get pod events, however, node events are getting a permissions error. Configuration of deployments, etc are the same... See error message below:

{"level":"error","error":"nodes \"zzz.yyy.vvv\" is forbidden: User \"system:serviceaccount:monitoring:event-exporter\" cannot get resource \"nodes\" in API group \"\" at the cluster scope","time":"2021-08-17T16:05:12Z","caller":"/app/pkg/kube/watcher.go:72","message":"Cannot list labels of the object"}

{"level":"error","error":"nodes \"zzz.yyy.vvv\" is forbidden: User \"system:serviceaccount:monitoring:event-exporter\" cannot get resource \"nodes\" in API group \"\" at the cluster scope","time":"2021-08-17T16:05:12Z","caller":"/app/pkg/kube/watcher.go:81","message":"Cannot list annotations of the object"}

**Comment by mmerickel** [comment]
Thanks for the example here - pasting a simplified version if it helps anyone.

We use role aggregation on the `view` role so don't want to hardcode this. The important part here on top of the default "view" ClusterRole, is the following.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-exporter-extra
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
```

You can bind that separately to the service account:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-exporter-extra
subjects:
  - kind: ServiceAccount
    namespace: kube-event-export
    name: event-exporter
```
