### ISSUE TITLE
Wrong yaml example for File sink in readme

### ISSUE THREAD

**Issue by tvi** [opsgenie/kubernetes-event-exporter#14]
Hello,
I was experimenting with this exporter and in yaml you have this example:
```
receivers:
  - name: "file"
    file:
      path: "/tmp/dump"
      layout: # Optional
```
but in source [code](https://github.com/opsgenie/kubernetes-event-exporter/blob/master/pkg/sinks/file.go) there is this:
```
Path   string                 `yaml:"file"`
```
which is causing `pkg/exporter/engine.go:19 > Cannot initialize sink error="open : no such file or directory" name=file`

Either example or source is misleading as it should be:
```
    file:
      file: "/tmp/dump"
      layout: # Optional
```
