### ISSUE TITLE
ConfigMap filtering events

### ISSUE THREAD

**Issue by cherry-ninja** [opsgenie/kubernetes-event-exporter#151]
Hello,

I can't filter out ConfigMap events with the next config:
``` yaml
logLevel: fatal
logFormat: json
route:
  routes:
    - match:
      - kind: "ConfigMap"
        receiver: "dump"
receivers:
  - name: "dump"
    stdout: { }
```

When I use `kind: "Pod"` everything works fine.
Does it mean this tools not support ConfigMap objects?

Best Regards
