### ISSUE TITLE
Cannot config it to send event from only one namespace to slack

### ISSUE THREAD

**Issue by barrowkwan** [opsgenie/kubernetes-event-exporter#154]
I am trying to configure kubernetes-event-exporter only send events from on namespace but it keep sending all events to slack

did I miss something?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - namespace: kube-utils
            - receiver: slack-test
        - match:
            - receiver: dump
    receivers:
      - name: dump
        stdout: {}
      - name: slack-test
        slack:
          token: xoxb-xxxxxxx
          channel: "xxxxxxxxx"
          message: "{{ .Message }}"
          title: Kube Event Staging
          author_name: Watcher
          footer: "kubernetes-event-exporter"
          fields:
            namespace: "{{ .Namespace }}"
            reason: "{{ .Reason }}"
            object: "{{ .InvolvedObject.Name }}"
```
