### ISSUE TITLE
Not able to delivery to files

### ISSUE THREAD

**Issue by zoechou** [opsgenie/kubernetes-event-exporter#157]
i use the following config to record kubernetes events,
i can find log via `kubectl logs -m monitor {pod-name}`
but fail to found logs in `/mnt/logs/kube-event-exporter`
is there any missing setting?

```
receivers:
- name: stdout
   stdout: {}
- name: fileoutput
   file:
     path: /mnt/logs/kube-event-exporter/current.log
route:
  routes:
  - drop:
    - type: Normal
    match:
    - kind: Pod|Deployment|ReplicaSet
      receiver: fileoutput
    - receiver: stdout
 ```

---

others, i found file type description
```
type FileConfig struct {
	Path       string                 `yaml:"path"`
	Layout     map[string]interface{} `yaml:"layout"`
	MaxSize    int                    `yaml:"maxsize"`
	MaxAge     int                    `yaml:"maxage"`
	MaxBackups int                    `yaml:"maxbackups"`
}
```
what's the unit of `maxsize` and `maxage`? kb/mb? hour/day?
thanks!!
