### ISSUE TITLE
Missing events

### ISSUE THREAD

**Issue by cristifalcas** [opsgenie/kubernetes-event-exporter#159]
Latest version is not catching most events.
Compared with version 0.10, nothing is showing up in my logs now

**Comment by omauger** [comment]
Hi,
Have you modified your configuration to increase the throttlePeriod to catch your missing events ?

If it's done, please give us the value you set and an example of missing event in Json.

**Comment by cristifalcas** [comment]
I set throttlePeriod from 5 to 300 and nothing changed.

Issues:
1. `pkg/kube/watcher.go` needs to import `_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"` in order to run it locally
2. It throws a lot of warnings about client-side throttling. I put this in `main.go` to fix it:
```
+       kubeconfig.QPS = 1e6
+       kubeconfig.Burst = 1e6
```
3. When the config is missing the namespace, seems it drops most of the events. Very few are printed. Hardcoding the namespace is showing a lot more events, but unfortunately only for that namespace
4. It doesn't receive events from custom sources (kube-downscaler).

Config:
```yaml
logLevel: debug
#logFormat: json
throttlePeriod: 5
# namespace: "custom-ns"
leaderElection:
  enabled: False
route:
  routes:
    - match:
        - receiver: "stdout"
receivers:
  - name: "stdout"
    stdout: {}
```

**Comment by mustafaakin** [comment]
I've run some manual tests in minikube cluster before I released this feature, but that small volume probably did not amount to something. Will test it more to find out what's going on.

I don't use gcp @cristifalcas does other auth mechanisms need to be imprted that way too? It seems similar how database drivers are used in Go

**Comment by cristifalcas** [comment]
@mustafaakin sorry, it didn't cross my mind that this is used on other clusters as well :) . I don't know how it is outside gcp.

I found the slowness in my case. The calls for `GetObject(reference, l.clientset, l.dynClient)` break everything. I think they return too slow? Returning `nil, nil` in GetLabelsWithCache and GetAnnotationsWithCache fixed all my issues.

I have to admit that there are hundreds of events per second in my cluster.
Maybe when it watches for all namespaces it gets overwhelmed when it tries to get the labels and annotations?

**Comment by superbrothers** [comment]
This is also the case in my environment. After upgrading to v0.11, event-exporter can no longer track events at all.

```
logLevel: error
logFormat: json
route:
  routes:
  - drop:
    - type: Normal
    match:
    - receiver: dump
      kind: Pod
receivers:
- name: dump
  stdout: {}
```

**Comment by DaveOHenry** [comment]
Most likely not related to the original issue, but I spotted missing events in an AKS cluster:
```
{
    "action": "Scheduling",
    "apiVersion": "v1",
    "eventTime": "2021-11-22T13:23:54.299870Z",
    "firstTimestamp": null,
    "involvedObject": {
        "apiVersion": "v1",
        "kind": "Pod",
        "name": "dummy-app-5d7b5796cf-zdz7z",
        "namespace": "foobar",
        "resourceVersion": "48010215",
        "uid": "e339d139-a27e-4ccc-8737-0db3a9620d6c"
    },
    "kind": "Event",
    "lastTimestamp": null,
    "message": "0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity rules, 3 node(s) didn't match pod anti-affinity rules.",
    "metadata": {
        "creationTimestamp": "2021-11-22T13:23:54Z",
        "name": "dummy-app-5d7b5796cf-zdz7z.16b9e1185e1665b8",
        "namespace": "foobar",
        "resourceVersion": "48010220",
        "uid": "205d3081-293e-473b-bf1a-8bb96c179606"
    },
    "reason": "FailedScheduling",
    "reportingComponent": "default-scheduler",
    "reportingInstance": "default-scheduler-kube-scheduler-v2-1234567890-hmccv",
    "source": {},
    "type": "Warning"
}
```
and
```
{
    "action": "Binding",
    "apiVersion": "v1",
    "eventTime": "2021-11-22T13:23:59.144478Z",
    "firstTimestamp": null,
    "involvedObject": {
        "apiVersion": "v1",
        "kind": "Pod",
        "name": "dummy-app-5d7b5796cf-zdz7z",
        "namespace": "foobar",
        "resourceVersion": "48010219",
        "uid": "e339d139-a27e-4ccc-8737-0db3a9620d6c"
    },
    "kind": "Event",
    "lastTimestamp": null,
    "message": "Successfully assigned foobar/dummy-app-5d7b5796cf-zdz7z to aks-system00-12345678-vmss000815",
    "metadata": {
        "creationTimestamp": "2021-11-22T13:23:59Z",
        "name": "dummy-app-5d7b5796cf-zdz7z.16b9e1197ed94a53",
        "namespace": "foobar",
        "resourceVersion": "48010246",
        "uid": "55631036-8044-4f91-8ffc-088e6dd88e2e"
    },
    "reason": "Scheduled",
    "reportingComponent": "default-scheduler",
    "reportingInstance": "default-scheduler-kube-scheduler-v2-1234567890-hmccv",
    "source": {},
    "type": "Normal"
}
```
Note the `null` value on "firstTimestamp" and "lastTimestamp". I guess this is the issue, because all other events contain correct values for these fields.

**Comment by ujo-trackunit** [comment]
Also seeing  issues with throttling in 0.11: 

```
I0103 11:46:44.912506       1 request.go:665] Waited for 1.157283329s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/apiregistration.k8s.io/v1beta1?timeout=32s
```

and fewer event. Issue with no events when upgrading was fix by not setting layout when using json as logFormat - my config looks like this: 

```
apiVersion: v1
data:
  config.yaml: |
    leaderElection: {}
    logFormat: json
    logLevel: info
    receivers:
    - file:
        path: /dev/stdout
      name: dump
    route:
      routes:
      - match:
        - receiver: dump
```
