### ISSUE TITLE
slack receiver should use webhook instead of token

### ISSUE THREAD

**Issue by aavileli** [opsgenie/kubernetes-event-exporter#30]
slack is depriciating slack tokens

**Comment by mustafaakin** [comment]
Then it's a very good first issue to contribute.

**Comment by wcarlsen** [comment]
I think the webhook sink is covering this use case, considering incoming webhooks in Slack (https://api.slack.com/messaging/webhooks). I tested it and it works flawless. Of course you need to play with the layout, but I think one can live with this.
Maybe consider deprecating the Slack sink and recommend the webhook sink instead, since Slack recommends not using legacy tokens?

**Comment by minac** [comment]
Hey @wcarlsen! I could use a hand, how did you configure the Slack webhook?

```
receivers:
      - name: "slack"
        webhook:
          endpoint: "https://hooks.slack.com/services/bla/bla/bla"
          headers:
            User-Agent: kube-event-exporter 1.0
```

Did you use any API Token? When setting up Incoming Webhooks in Slack there are no tokens now, right?

Thanks!
