### ISSUE TITLE
AWS ElasticSearch not getting any data

### ISSUE THREAD

**Issue by luciangutu** [opsgenie/kubernetes-event-exporter#34]
Hi.

I'm having trouble seeing the data from event-exporter in AWS ElasticSearch.

config.yaml
```
route:
  routes:
    - match:
        - receiver: "es-dump"
receivers:
  - name: "es-dump"
    elasticsearch:
      hosts:
        - "https://vpc-k8s.us-east-1.es.amazonaws.com:443"
      index: "kube-events"
```

I can see the logs in the event-exporter:
```
2020-03-30T07:30:35Z DBG app/pkg/exporter/channel_registry.go:56 > sending event to sink event="Started container event-exporter" sink=es-dump
```
But the kube-events has no data (that 1 was a curl test that I've did to check the connection):
```
green open kube-events               9vZMUP-5S3KY8BNvpBLVVg 5 1        1  0   9.4kb   4.7kb
```

Help, please?
