### ISSUE TITLE
How do I remap whole kubernetes event to key

### ISSUE THREAD

**Issue by UtsavChokshiCNU** [opsgenie/kubernetes-event-exporter#41]
I am trying to do this :
```
receivers:
      - name: "my-recv"
        webhook:
          endpoint: "http://example.com"
          headers:
            User-Agent: kube-event-exporter 1.0
          layout:
            data: "{{ . }}"
```
So I want matched kubernetes event to be sent under data key in JSON like :
```
{
  "data": {
    "metadata": {},
    "reason": "SuccessfulCreate",
    "message": "Created pod: x-6htmw",
    "source": {
      "component": "replicaset-controller"
    },
    "count": 1,
    "type": "Normal",
    "eventTime": "None",
    "reportingComponent": "",
    "reportingInstance": "",
    "involvedObject": {
      "kind": "ReplicaSet",
      "namespace": "x",
      "name": "x-779848ccb7",
      "uid": "x",
      "apiVersion": "apps/v1",
      "resourceVersion": "x",
      "labels": {
        "app": "x"
      },
      "annotations": {
        "serving.knative.dev/creator": "system:serviceaccount:flux:flux"
      }
    }
  }
}
```
It is failing to send. Can you help me out ?

**Comment by mustafaakin** [comment]
You don't have to use the layout, it's optional, it would default to serializing the whole object as is.

**Comment by mustafaakin** [comment]
Oh, I see you want it to be under data: 
It would require considerable changes to codebase, right now your best bet is to write everything open as template.

**Comment by mustafaakin** [comment]
```
          layout:
            data:
                reason: {{ .Reason }}
                message: {{ .Message }} 
```
