### ISSUE TITLE
match string regex issue

### ISSUE THREAD

**Issue by kisshore** [opsgenie/kubernetes-event-exporter#51]
I'm trying to collect my events with reason **FailedCreatePodContainer**, but when event occurred  with reason **FailedCreate** also collected to my elastic search. Here is my config.yaml
```
apiVersion: v1
data:
  config.yaml: |
    route:
      match:
        - reason: "FailedCreatePodContainer"
        - receiver: "elastic"
      drop:
        - type: "Normal"
    receivers:
      - name: "elastic"
        elasticsearch:
          hosts:
          - http://elastic:9200
          index: kube-events
kind: ConfigMap

```
I saw below code in router.go , do we need to modify or is there any other way to handle this regex.

```
func matchString(pattern, s string) bool {
	matched, _ := regexp.MatchString(pattern, s)
	return matched
}
```
