### ISSUE TITLE
Support kustomize

### ISSUE THREAD

**Issue by nstogner** [opsgenie/kubernetes-event-exporter#55]
Kustomize is a popular tool for deploying to kubernetes. It could be supported by adding a `kustomization.yaml` file into the `deploy/` dir:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-roles.yaml
- 01-config.yaml
- 02-deployment.yaml
```

To make the namespace customizable, it would be nice to split the `Namespace` object definition out to another file (`00-namespace.yaml` - not included in the `.resources` array above).

A user's `kustomization.yaml` might look like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/opsgenie/kubernetes-event-exporter//deploy?ref=v0.8
```
