### ISSUE TITLE
Log to stdout

### ISSUE THREAD

**Issue by mrueg** [opsgenie/kubernetes-event-exporter#59]
We would like to run this within a container and a service account to reach kubernetes API, it would be awesome to log events directly to stdout. 

I see that console output is still on the TODO in the readme.md, are there any plans to get it in?

**Comment by mustafaakin** [comment]
The file name can be changed as /dev/stdout but rotation should not be used. But adding a proper console output can also be simple but would be duplicate work.

**Comment by mrueg** [comment]
Thanks, that's a good idea. I think it would be good to add this to the README.md

**Comment by mustafaakin** [comment]
Yes, I should add this. For reference unil then:

```
logLevel: error
logFormat: json
route:
  routes:
    - match:
        - receiver: "dump"
receivers:
  - name: "dump"
    file:
      path: "/dev/stdout"
```
