### ISSUE TITLE
feature: disabling log labels

### ISSUE THREAD

**Issue by kfirfer** [opsgenie/kubernetes-event-exporter#74]
Feature request:

To be able disable to scrape and output object labels

because there too many duplication data, and the labels is almost always the same from event to event

**Comment by kfirfer** [comment]
Hi

This is example of the configmap I using:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-config
  namespace: event-exporter
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "dump"
    layout:
      eventType: "kube-event"
      createdAt: "{{ .GetTimestampMs }}"
      details:
        message: "{{ .Message }}"
        reasonss: "{{ .Reason }}"
        tip: "{{ .Type }}"
        count: "{{ .Count }}"
        kind: "{{ .InvolvedObject.Kind }}"
        name: "{{ .InvolvedObject.Name }}"
        namespace: "{{ .Namespace }}"
        component: "{{ .Source.Component }}"
        host: "{{ .Source.Host }}"
    receivers:
      - name: "dump"
        file:
          path: "/dev/stdout"

```

Using Layout but still could see labels in the json output:
```
{
  "metadata": {
    "name": "zigi-server-5f8c964bdd-rz5fv.162f10736d230b61",
    "namespace": "zigi-test",
    "selfLink": "/api/v1/namespaces/zigi-test/events/zigi-server-5f8c964bdd-rz5fv.162f10736d230b61",
    "uid": "f73d9a5b-1a7e-42e7-b420-7715c5f645f1",
    "resourceVersion": "4169884",
    "creationTimestamp": "2020-08-27T07:48:00Z",
    "managedFields": [
      {
        "manager": "kubelet",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2020-08-27T07:48:00Z"
      }
    ]
  },
  "reason": "Started",
  "message": "Started container zigi-server",
  "source": {
    "component": "kubelet",
    "host": "nuc02"
  },
  "firstTimestamp": "2020-08-27T07:48:00Z",
  "lastTimestamp": "2020-08-27T07:48:00Z",
  "count": 1,
  "type": "Normal",
  "eventTime": null,
  "reportingComponent": "",
  "reportingInstance": "",
  "involvedObject": {
    "kind": "Pod",
    "namespace": "zigi-test",
    "name": "zigi-server-5f8c964bdd-rz5fv",
    "uid": "6b0c0927-e9c7-4874-81ff-557173a1327a",
    "apiVersion": "v1",
    "resourceVersion": "4169853",
    "fieldPath": "spec.containers{zigi-server}",
    "labels": {
      "app.kubernetes.io/instance": "zigi-server",
      "app.kubernetes.io/name": "zigi-server",
      "pod-template-hash": "5f8c964bdd"
    },
    "annotations": {
      "rollme": "9brsZ"
    }
  }
}
```
