### ISSUE TITLE
Events not indexed by elasticsearch 6.0: can kubernetes-event-exporter be made compatible with older versions?

### ISSUE THREAD

**Issue by marcindulak** [opsgenie/kubernetes-event-exporter#77]
I was trying to send events to an elasticsearch receiver, but no events were indexed.  A "fix" that helps consists of  setting `req.DocumentType = "documentType"` after the lines https://github.com/opsgenie/kubernetes-event-exporter/blob/336fa39c4c53ac68012e602dc13a22964764228b/pkg/sinks/elasticsearch.go#L129-L131

In order to diagnose the problem a few lines added after https://github.com/opsgenie/kubernetes-event-exporter/blob/336fa39c4c53ac68012e602dc13a22964764228b/pkg/sinks/elasticsearch.go#L133-L136 for printing the response from elasticsearch

```
        buf := new(bytes.Buffer)
        buf.ReadFrom(resp.Body)
        newStr := buf.String()
        fmt.Printf("resp.Body %s\n", newStr)
```

returned:

```
resp.Body {"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_doc]"}],"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', found: [_doc]"},"status":400}
```

This seems like a known problem in some older elasticsearch versions.
The problem is "fixed" by setting `req.DocumentType = "documentType"`

```
git diff pkg/sinks/elasticsearch.go
diff --git a/pkg/sinks/elasticsearch.go b/pkg/sinks/elasticsearch.go
index 3306faa..e873629 100644
--- a/pkg/sinks/elasticsearch.go
+++ b/pkg/sinks/elasticsearch.go
@@ -130,6 +130,8 @@ func (e *Elasticsearch) Send(ctx context.Context, ev *kube.EnhancedEvent) error
                req.DocumentID = string(ev.UID)
        }
 
+        req.DocumentType = "documentType"
+
        resp, err := req.Do(ctx, e.client)
        if err != nil {
                return err
```

The 01-config.yaml is as follows, and I'm using https://github.com/opsgenie/kubernetes-event-exporter/releases/tag/v0.8

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "dump"
            - receiver: "elasticsearch"
    receivers:
      - name: "dump"
        file:
          path: "/dev/stdout"
      - name: "elasticsearch"
        elasticsearch:
          hosts:
            - "https://a-cluster-in-aws...es.amazonaws.com"
          index: "kube-events"
          indexFormat: "kube-events-{2006.01.02}"
```
