### ISSUE TITLE
Filtering not done properly on Type

### ISSUE THREAD

**Issue by aronneagu** [opsgenie/kubernetes-event-exporter#80]
I have the following config
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    #logLevel: debug
    logLevel: error
    route:
      routes:
        - match:
          - type: "Warning"
          - receiver: "dump"
    receivers:
      - name: "dump"
        file:
          path: "/dev/stdout"
```

I am seeing events also that have type=Normal. Am I doing something wrong, or the filtering doesn't work as expected?

Using version opsgenie/kubernetes-event-exporter:0.8
Kube version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
