### ISSUE TITLE
Make config.yaml more dynamic and flexible with environment variables

### ISSUE THREAD

**Issue by bygui86** [opsgenie/kubernetes-event-exporter#93]
Hi guys,
first of all thank you for this amazing tool!

I tried to deploy k8s-event-exporter to dump events to ES and it worked perfectly, but I have a concern about how to configure everything properly.
Assuming:
- I have auth and TLS enabled for ES, so in the config.yaml I have to provide such info.
- Username, password and TLS cert are managed by the eck official operator.

Is there a way to inject ES username, password and TLS cert in the config.yaml without having to manually hard-coding them?
For example using placeholders like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-event-exporter-es
data:
  config.yaml: |
    logLevel: info
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "elastic"
    receivers:
      - name: "elastic"
        elasticsearch:
          hosts:
            - "https://logging-es-http.logging.svc.cluster.local:9200"
          indexFormat: "k8s-events-{2006-01-02}"
          username: ${ES_USERNAME}
          password: ${ES_PASSWORD}
          useEventID: false
          tls:
            insecureSkipVerify: true
```

Note: of course I switched from ConfigMap to Secret ;)
