### ISSUE TITLE
Elasticsearch Receiver not working with %{+YYYY-MM-dd} on indexFormat

### ISSUE THREAD

**Issue by moronmon** [opsgenie/kubernetes-event-exporter#95]
Hi, I got an issue using Elasticsearch receiver. If I put %{+YYYY-MM-dd} on my indexFormat, it failed to send the event to my elasticsearch, and there are no error logs on the event-exporter logfiles. Is it event exporter not support the format or I use the wrong format?
Here's my receiver config
```
      - name: "es_dump"
        elasticsearch:
          index: k8s-event
          hosts:
          - http://192.168.88.231:9200
          indexFormat: k8s-event-%{+YYYY-MM-dd}
          username: username
          password: password
```
