### ISSUE TITLE
Unable to regiater Teams sink

### ISSUE THREAD

**Issue by PaoloneM** [opsgenie/kubernetes-event-exporter#97]
I'm trying to use the MS Teams integration. This is my config:

```
    logLevel: debug
    logFormat: json
    route:
      # Main route
      routes:
        # This route allows dumping all events because it has no fields to match and no drop rules.
        - match:
            - receiver: "dump"
        - match:
            - receiver: "ms_teams"
        # This starts another route, drops all the events in *quality* namespaces and Normal events 
        # for capturing critical events 
        - drop:
            - namespace: "*quality"
            - type: "Normal"
            - receiver: "slack"
    receivers:
      - name: "dump"
        elasticsearch:
          indexFormat: "kube-events-{2006-01-02}"
          cloudID: "..."
      - name: "slack"
        slack:
          token: "xoxb-1263858707105-...."
          channel: "#k8s-events"
          message: ":boom: {{ .Message}}"
          fields:
            type: "{{ .Type }}"
            message: "{{ .Message }}"
            namespace: "{{ .Namespace }}"
            reason: "{{ .Reason }}"
      - name: "ms_teams"
        teams:
          endpoint: "https://outlook.office.com/webhook/627257d1-ff24-...."
```

Slack receives messages, while MS Teams doesn't. In pod's logs I found this:

```
{"level":"info","name":"dump","type":"*sinks.Elasticsearch","time":"2020-12-13T14:16:37Z","caller":"/app/pkg/exporter/engine.go:25","message":"Registering sink"}
{"level":"info","name":"slack","type":"*sinks.SlackSink","time":"2020-12-13T14:16:37Z","caller":"/app/pkg/exporter/engine.go:25","message":"Registering sink"}
```
but nothing about Teams.

Am I missing something? Layoput should be optional as per documentation, right?

Thanks.
Paolo
