### ISSUE TITLE
Webhook config for Loki

### ISSUE THREAD

**Issue by bygui86** [opsgenie/kubernetes-event-exporter#99]
Hi guys,

I search for the right configuration to push events directly to Loki.

I tried this one but I don't see anything in Loki, just stdout logs:
```yaml
logLevel: debug
logFormat: json
route:
  routes:
    - match:
        - receiver: "stdout"
        - receiver: "loki"
receivers:
  - name: "stdout"
    file:
      path: "/dev/stdout"
  - name: "loki"
    webhook:
      endpoint: "http://loki.logging.svc.cluster.local:3100/loki/api/v1/push"
      headers:
        User-Agent: "kube-event-exporter 0.9"
        Content-Type: "application/json"
```

What's wrong in my config?

Thanks in advance for any help!

**Comment by erkiesken** [comment]
That Loki api endpoint expects json to be in specific format. Try this config to see if it works:

```
      - name: "loki"
        webhook:
          endpoint: "http://loki.logging.svc.cluster.local:3100/loki/api/v1/push"
          headers:
            Content-Type: application/json
            User-Agent: kube-event-exporter 0.9
          layout:
            streams:
              - stream:
                  eventType: "kubernetes-event"
                values:
                  - "{{ .GetTimestampMs }}000"
                  - "{{ toJson . }}"
```

**Comment by erkiesken** [comment]
And if Loki is anyway capturing your container logs when just the stdout receiver will be also enough to get the k8s event info into Loki.

**Comment by bygui86** [comment]
@erkiesken thanks a lot for the suggestion!
I will try that configuration soon.
Is there a description of the `layout.streams` configuration?
I found a brief explanation of `layout` but nothing about `streams` or `{{ toJson . }}`
Should I look here http://masterminds.github.io/sprig/ ?

> And if Loki is anyway capturing your container logs then just the stdout receiver will be also enough to get the k8s event info into Loki.

I'm already doing this, but in some cases it takes a bit time and we should react really fast.

**Comment by erkiesken** [comment]
`layout` just defines a custom object format to output, I just followed the [example from readme](https://github.com/opsgenie/kubernetes-event-exporter#customizing-payload) and the [loki push example here](https://grafana.com/docs/loki/latest/api/#examples-4). So everything under `layout` maps yaml to expected json struct.

**Comment by bygui86** [comment]
Thanks @erkiesken 
I will try what you suggested!

**Comment by deng47** [comment]
I would like to share my version of loki receiver here:
```
    receivers:
      - name: "loki"
        webhook:
          endpoint: "http://hostname:3100/loki/api/v1/push"
          headers:
            Content-Type: application/json
            User-Agent: kube-event-exporter 0.9
          layout:
            streams:
              - stream:
                  severity: "{{ .Type }}"
                  reason: "{{ .Reason }}"
                  name: "{{ .InvolvedObject.Name }}"
                  namespace: "{{ .InvolvedObject.Namespace }}"
                  kind: "{{ .InvolvedObject.Kind }}"
                  host: "{{ .Source.Host }}"
                  component: "{{ .Source.Component }}"
                values:
                - - "{{ .GetTimestampMs }}000000"
                  - "{{ .Message }}"
```
